### ISSUE TITLE
outdated version of electron

### ISSUE THREAD

**Issue by pr0fsmith** [erikdubois/nixos-configurations#1]
I get the following error after running copy.sh

`
building the system configuration...
trace: warning: The option `services.xserver.xkbVariant' defined in `/etc/nixos/configuration.nix' has been renamed to `services.xserver.xkb.variant'.
trace: warning: The option `services.xserver.layout' defined in `/etc/nixos/configuration.nix' has been renamed to `services.xserver.xkb.layout'.
trace: warning: The option `services.avahi.nssmdns' defined in `/etc/nixos/configuration.nix' has been renamed to `services.avahi.nssmdns4'.
trace: warning: The option `services.xserver.displayManager.sddm.enable' defined in `/etc/nixos/configuration.nix' has been renamed to `services.displayManager.sddm.enable'.
trace: warning: The option `services.xserver.displayManager.autoLogin' defined in `/etc/nixos/configuration.nix' has been renamed to `services.displayManager.autoLogin'.
error:
       … while calling the 'head' builtin

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 'etcher' has been removed because it depended on an insecure version of Electron

################################################################
################################################################
`

**Comment by erikdubois** [comment]
thanks lets remove etcher then
